Avoid CMake duplicate symbol error
When configuring CGNS with a CMake-build/install of HDF5, the `add_executable(h5dump IMPORTED)` command will generate the error:
```
CMake Error at CMakeLists.txt:219 (add_executable):
  add_executable cannot create imported target "h5dump" because another
  target with the same name already exists.
```
Since the file `hdf5-targets.cmake` contains the same command.  I'm not sure if this if branch is entered if HDF5 is installed via autotools, but in my testing I got a valid build with both cmake and autotools HDF5 builds.