Revert the !DEC$ changes because it breaks for make test using intel compilers on linux:
    ifort  -I.. -o cgwrite_F03 cgwrite_f03.F ../lib/libcgns.a
    /tmp/ifortNudbSB.o: In function `MAIN__':
    cgwrite_f03.F:(.text+0xa29): undefined reference to `cg_goto_f'
    cgwrite_f03.F:(.text+0x1166): undefined reference to `cg_array_write_f'
    cgwrite_f03.F:(.text+0x11c7): undefined reference to `cg_goto_f'
    cgwrite_f03.F:(.text+0x16ca): undefined reference to `cg_goto_f'
    cgwrite_f03.F:(.text+0x19d7): undefined reference to `cg_goto_f'
    cgwrite_f03.F:(.text+0x1b23): undefined reference to `cg_goto_f'
    cgwrite_f03.F:(.text+0x1c0a): undefined reference to `cg_array_write_f'